Задание 1

In [9]:
import numpy
n = int(input('Введите число: '))
NP = (numpy.arange(n))[::-1]
print(NP)

Введите число: 5
[4 3 2 1 0]


Задание 2

In [18]:
import numpy
n = int(input('Введите число: '))
a = numpy.zeros((n, n), int)
NP = (numpy.arange(n))[::-1]
numpy.fill_diagonal(a, NP)
result = sum(NP)
print (a)
print ('сумма: ' + str(result))

Введите число: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
сумма: 10


Задание 3

In [24]:
import numpy
x = numpy.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
y = numpy.array([4, 12, -3]) 
result = numpy.linalg.solve(x, y)
print ('X = ' + str(result[0]))
print ('Y = ' + str(result[1]))
print ('Z = ' + str(result[2]))

X = 0.4666666666666668
Y = 3.844444444444444
Z = -5.555555555555555


Задание 4

In [69]:
import numpy
users_stats = numpy.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    numpy.int32
)
next_user_stats = numpy.array([0, 1, 2, 0, 0, 0])
result = users_stats[numpy.argmax(numpy.dot(next_user_stats, users_stats.T)/(numpy.linalg.norm(users_stats)*numpy.linalg.norm(next_user_stats)))]
print (result)

[1 1 2 1 0 0]
